spring:
  application:
    name: cafer

  datasource:
    url: jdbc:mysql://localhost:3306/cafer
    username: cafer
    password: cafer
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
          use_sql_comments: true
          generate_statistics: true

  server:
    port: 8080

  logging:
    level:
      root: INFO
      org.springframework: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

dgs:
  graphql:
    introspection:
      enabled: true
    graphiql:
      enabled: true
      title: "Cafer"

management:
  metrics:
    dgs-graphql:
      enabled: true

