spring:
  application:
    name: cafer

dgs:
  graphql:
    introspection:
      enabled: true
    graphiql:
      enabled: true
      title: "Cafer"

management:
  metrics:
    dgs-graphql:
      enabled: true