type Cafe {
    id: ID
    name: String
    location: String
    description: String
}

type Query {
    cafes: [Cafe]
    cafe(id: ID!): Cafe
}

type Mutation {
    addCafe(name: String!, location: String!, description: String!): Cafe
    updateCafe(id: ID!, name: String, location: String, description: String): Cafe
    deleteCafe(id: ID!): String
}
