version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cafer
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cafer
      MYSQL_USER: cafer
      MYSQL_PASSWORD: cafer
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: